### ISSUE TITLE
pg_bkrs1

### ISSUE THREAD

**Issue by katsunori-yasuda** [interface-1981/book_management#1]
![pg_bkrs1](https://user-images.githubusercontent.com/25840552/33938869-5ccd1c62-e04c-11e7-90b8-c7afacc8a688.png)

**Comment by ghost** [comment]
Issueを保存しなくても、画像をドラッグアンドドロップしてできるURLをコピペすればWikiで使えるよ～。
下のURLをWikiにコピペすればOK。
Wikiに直接ドラッグアンドドロップできればいいんだけどね。できないからちょっと面倒だね。
<img width="466" alt="default" src="https://user-images.githubusercontent.com/25605159/33942202-7cdd1636-e058-11e7-9406-412d5b619c0c.PNG">
